name: maxfleetwood
favicon: null
layout_spectrum: 0.9863172539044172
typography_spectrum: 0.4665612948592752
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.21715556015260518
  lightness: 0.3036932668182999
  saturation: 0.41772081702947617
  rhythmicContrast: 0.38313871365971863
purpose: []
